bootstrap.servers=kafka:9092
schema.registry.url=http://kafka-schema-registry:8081
application.id=sensor-normalizer

topic.humidity.raw=mqtt_humidity_raw
topic.temperature.raw=mqtt_temperature_raw
topic.location.raw=mqtt_location_raw
topic.state.raw=mqtt_state_raw

topic.humidity.out=sensor.humidity.v1
topic.temperature.out=sensor.temperature.v1
topic.location.out=sensor.location.v1
topic.state.out=sensor.state.v1
topic.parse.errors=sensor.parse.errors