{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pvz-infra.fullname" . }}-postgres
  labels:
    {{- include "pvz-infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: {{ .Values.servicePorts.postgresService }}
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pvz-infra.fullname" . }}-postgres
  labels:
    {{- include "pvz-infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.images.postgres }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              hostPort: {{ .Values.servicePorts.postgresHost }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U {{ .Values.postgres.user }} -d {{ .Values.postgres.db }}
            initialDelaySeconds: 15
            periodSeconds: 5
          volumeMounts:
            - name: db-init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-init
          hostPath:
            path: {{ .Values.hostPaths.dbInit | quote }}
            type: Directory
        - name: postgres-data
          emptyDir: {}
{{- end }}
